org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Meta
mod.id=ccshared
mod.name=cc: Shared
mod.group=com.mrchuw.ccshared
mod.version=1.0.0
mod.description=Shared folder for CC: Tweaked computers.
mod.authors=MrChuw
mod.repo_url=https://github.com/MrChuw/cc-shared
mod.license=GPLv2
mod.logo=assets/ccshared/icon.png

# Loader deps comuns
deps.fabric-loader=0.19.5

# Publish
publish.curseforge=
publish.modrinth=
